version: 0.4.0-build-{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  project_feed: true
before_build:
- cmd: dotnet restore source\LibUISharp\LibUISharp.csproj
build:
  project: source\LibUISharp\LibUISharp.csproj
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: normal
artifacts:
- path: '**\*.nupkg'
  name: LibUISharp
deploy:
- provider: NuGet
  api_key:
    secure: IZppUyZ6HPKxAYqqlqWV8CPbsYJkbJGncDFIpm+lSNwGPEjynq1NsGZ4H5K/ryHh