version: 0.3.5-alpha-{build}
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
environment:
  LIBUISHARP_PRERELEASE: 1
nuget:
  project_feed: true
before_build:
- cmd: dotnet restore LibUISharp.sln
build:
  project: LibUISharp.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: detailed
artifacts:
- path: '**\*.nuget'
  name: LibUISharp
deploy:
- provider: NuGet
  api_key:
    secure: IZppUyZ6HPKxAYqqlqWV8CPbsYJkbJGncDFIpm+lSNwGPEjynq1NsGZ4H5K/ryHh
  on:
    LIBUISHARP_PRERELEASE: 0